== Personal Reports

=== Nathanael Fässler
This project was definitely a personal highlight of this semester and of my time at OST in general. We created a video game from start to finish and experienced every aspect of game development. We began planning in the previous semester, brainstormed ideas for gameplay and game rules, created our own 3D models, programmed the game systems, conducted user tests and finally published it on Steam.

Game development is my favorite field within software engineering, so I am very grateful that we were even allowed to pursue such an unconventional SE Project and that it worked out so well.

Making a game in Unity introduced challenges that most other groups didn't have. Testing game code is very difficult and the architecture is not as obvious as in projects that just consist of a frontend and backend. At the same time I find writing code for a game much more exciting than implementing business logic. The programming involved a lot of algorithmic problem solving and since our game is 3D, many programming tasks involved vector mathematics. It felt rewarding to finally apply the theoretical concepts learned in DMI (Diskrete Mathematik für Informatik) and AlgDat (Algorithmen und Datenstrukturen).

The initiative to make a game and the initial idea came from me, so we decided that I would take the role of the Product Owner. I was responsible for the planning and I learned how to manage a backlog effectively. I underestimated how difficult it is to create tasks with sufficiently clear requirements and instructions and I see potential to improve my communication skills. Since I mainly focused on the product and planning, I was not involved in the CI/CD process which I consider a missed opportunity and something I would like to learn more about in the future.

In retrospect I would definitely choose to make a game again. However, for future students I would only recommend developing a game in SE Project if the following conditions are met:
+ The team members are already very familiar with the game engine or have enough time to learn it *before* the semester starts.
+ The members define one person who is responsible for decisions about the game's contents or they have very good communication skills and are able to make decisions time efficiently.
+ The game idea needs to be very small but designed to be extensible. The game should be simple enough to be developed within a few weeks, while still allowing additional features and content to be added. Ideally, the project is always in a state where it could be considered a finished product.

=== Dominik Wyss
When our team first discussed possible project ideas, I was not very enthusiastic about developing a game. In general, game projects were not strongly recommended, and none of us had any previous experience with game development. From my perspective, it also seemed unlikely that the project would be very useful for my future career, since becoming a game developer has never been one of my goals.

Despite these concerns, I spent a lot of time discussing ideas and planning the project together with the team. Once we decided to move forward with the idea, I wanted to contribute as much as possible and help make the project successful. Even though I do not see myself working on game projects again in the future, I have always been interested in games as a hobby. Over the years, I have played many different games and completed quite a few of them. Because of this, I was able to bring ideas and observations from successful games into discussions about our own project. As a computer science student, I also tend to look at games differently and think about how certain mechanics and systems could be implemented in software and adapted to our own requirements.

One aspect that surprised me positively was the collaboration within the team. Teamwork is often difficult, especially when people have different opinions about how something should be implemented. There were several situations where not everyone agreed with a decision. Sometimes a team member strongly preferred one solution, but after discussing it, the team decided to follow a different approach. This was not always easy to accept, but in most cases people respected the final decision and continued working towards the same goal.

I think this was one of the reasons why our project was successful. Even when opinions differed, the team remained constructive and focused on finding a solution instead of proving who was right. We consistently attended meetings, completed our tasks, and supported each other throughout the semester. Looking back, I was impressed that we managed to maintain this level of commitment until the very end and successfully deliver a finished product.

For future projects, I would personally prefer to work on a more traditional software application. I am more interested in solving technical problems through code, working with algorithms, or designing software systems. While I appreciate the experience of developing a game, I realized that I am less interested in areas such as player movement, visual design, or building a complete 3D world. My interests are more focused on software that is driven by functionality and technical problem-solving.

Overall, the project challenged some of my initial expectations. Even though I would not choose a game project again, I learned a lot about teamwork, planning, and working on a type of software that was completely new to me. The experience showed me that a team can still work effectively even when members have different opinions and preferences. These lessons will be valuable in future software projects regardless of the field I work in.


=== Cedric Cathomas

I had never worked with Unity before and had never created a game, so the whole project was new territory for me. C\# was already my favorite language, which gave me at least some familiar ground to stand on. I was genuinely excited, because I love video games and building one finally let me peek behind the curtain and see how everything actually connects. At the same time I was a little nervous, since I had no experience and knew it would mean extra effort to learn everything from scratch. But I committed to it, and preparing well before the semester started kept that excitement going.

As the team's UI Architect I implemented our entire UI and the dependencies that connect it to the game logic. I built most of the things that make up the UI, such as the inventory, the hotbar, the crafting stations, the GlowCore and the whole menu and settings, and I was also able to contribute to some of the logic elements, which I really enjoyed because it showed me how a game actually works under the hood. Almost everything was new to me, since it was my first time building both a game and of course a game UI. Unity itself, the scenes, and the canvas were completely unfamiliar, but the preparation beforehand and the time we invested as a team to learn the basics helped a lot. It was a very rewarding process to see how good a UI can look once you understand how it is done. The architecture also gave me the chance to apply the principles we learned in SEP2: I really learned how to make use of dependency injection together with the open-closed and single-responsibility principles to create a clean and extensible architecture where we could add new UIs as they came. What I value most is that I now know how those principles actually look and feel to use in production. I will never forget what dependency injection is or why it matters. I was also surprised how useful the tooling around the project is, from the workflows and GitHub Actions to the test runner, the sprites and the audio system. On top of that I took on the role of project manager, making sure everything was done on time and that everyone could do their work. I enjoyed seeing the project from that different perspective, even though I prefer doing the tasks over managing them. My personal highlight was the menu scene and the extendable, reusable inventory I built. It was a great moment when the controls finally worked together with the game and once the audio system was in place we suddenly had a full game, with a main menu, settings, a pause screen and all the UIs you know from the classic games of my childhood. Everything fit together and it felt like we had made it.

I have had work experience where teamwork mattered, but honestly it is no comparison to how well we worked together in our team of four. I did not know it was possible for everyone to contribute so much and to be so dedicated to helping each other out, especially in a uni project. Responses were quick most of the time, the communication was always there and there were always ideas, questions and discussions. Seeing the others so motivated motivated everyone in turn and that is what pushed me personally to give my best. The sprint plannings and meetings gave us a great overview and helped us keep track of every change and every ongoing problem. We did tend to plan too much, but that was because we wanted to do a lot without really knowing how long each task would take, which made sense given the unfamiliar tools and the fact that almost every task involved something new. A game also has so many different areas that a team of four, not working on it full-time, can quickly reach its limits. The clearest problems we had were the merge conflicts in the main scene. Coordinating our changes was very hard, especially in the beginning, because of all the dependencies and to this day I do not know how we could have avoided them completely. We did our best by communicating the changes that were likely to cause conflicts, but in the end that is simply a problem you face when building a game in a larger team where tasks sometimes overlap. Compared to my old job, this team was definitely better and for such a big and unusual project I think we really got the best out of it.

Of course there is always room for improvement. Sometimes reviews took too long, but considering we only worked on the project around eight hours a week, it is hard to expect someone to look at changes instantly, especially the bigger ones. It was also difficult to understand the actual goal or implementation of a task at the beginning, which needed a lot of additional communication and rework. Ideally tasks would be planned through well enough not to raise so many questions, but that is hard when everyone also has to program, plan and document at the same time. I personally did not expect the game to be so complex or to have so many different systems, from the UI and the audio system to the scriptable objects and the logic, and at some point it became quite overwhelming. That is the main reason I would not build a game again in this setting. To do it cleanly it would need a dedicated product owner with an exact vision, a separate architect, developers who implement based on clear descriptions and a lot more time. The testing alone is very time-consuming and having to learn all the new concepts on top of that was one step too many. Still, I do not regret it, because I was able to learn so much and take away so many things for my career.

Overall I am very happy with our product and with everything I was able to learn. We made a fantastic game with a genuinely addictive drive and a lot of possibilities to try out. The path was not an easy one, but the result was definitely worth it and each of us carried a lot of responsibility in our own area. As honest as I can be, I would not do it again, because the project pushed me to my limits with its complexity and all the dependencies and potential issues, which made it at times too stressful. This only worked because everyone truly contributed. With a different team I could imagine this being impossible to pull off so well, so in that sense we were lucky to have a Product Owner who burned for the project and carried us along with his passion. It took a lot of energy, but it gave back even more and the result surpassed my expectations. I am very proud of what we built.

=== Yoris Kucera

When the team first started collecting project ideas, I was immediately drawn to the thought of building a game. I had made a few attempts at game development on my own in the past, none of which I ever really finished, so the idea of seeing a complete game through from start to finish, this time with a committed team behind it, was genuinely exciting to me. It felt like a chance to finally turn something I had only ever dabbled in into a real product.

That initial enthusiasm shifted fairly quickly once we were deep into development. I came to realize that game development is not really a field I am passionate about, and the main reason is how constrained you are by the architecture that Unity lays out for you. So much of the work is about fitting your code into the engine's component model, its scene structure, and its lifecycle, rather than designing systems the way you would approach them in a more traditional software project. For someone who enjoys the design and structuring side of software engineering, constantly having to bend around the engine's conventions was often more frustrating than rewarding.

Despite that, the role I took on ended up being the part of the project I valued most. As the team's Software Architect I was responsible for a large share of the architectural decisions in the codebase. I spent a lot of time thinking about how our systems should be separated, how components should communicate, and how to keep things extensible so that new features could be added without rewriting what already existed. Working through those decisions, and seeing the rest of the team build on top of the structure we agreed on, was where I learned the most and where I felt I contributed the most value.

The part I genuinely enjoyed the most, however, was designing the low-res rendering architecture and the highlight/outline system. This was where I got to write shaders and work much closer to the rendering pipeline, and it turned out to be the kind of self-contained, technical problem solving I really like. There was a lot of satisfaction in getting the low-res look exactly right and in making interactable objects clearly stand out with a clean outline. Unlike a lot of the gameplay work, these systems gave me room to actually engineer a solution end to end, and I was proud of how they came together.

Overall I am happy with the final product and with what we managed to build as a team. We delivered a complete, mostly polished game, and I learned a lot along the way, both about software architecture and about the parts of development I do and do not enjoy. That said, my biggest takeaway is that, in the future, I would most likely not choose to make a game in a project like this again. I appreciate the experience and do not regret it, but I now know that my interests lie more in traditional software engineering, where I have the freedom to design systems on my own terms rather than within the boundaries an engine sets for me.
