name: Lint

on:
  push:
    branches: [main, dev]
    tags: ['v*.*.*']
    paths-ignore:
      - 'doc/**'
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - 'doc/**'

permissions:
  contents: read

env:
  SOLUTION_FILE: glowcore.sln
  LINT_PROJECT_FILE: Tools/Lint/GlowCore.Lint.csproj
  UNITY_EDITOR_PATH: /home/yoris/Unity/Hub/Editor/6000.3.9f1/Editor/Unity

jobs:
  lint:
    name: Lint Code
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      
      - name: Activate Unity License
        uses: buildalon/activate-unity-license@v2
        with:
          license: 'Personal'
          username: ${{ secrets.UNITY_EMAIL }}
          password: ${{ secrets.UNITY_PASSWORD }}

      - name: Generate Project Files
        run: |
          "${{ env.UNITY_EDITOR_PATH }}" -batchmode -nographics -quit \
            -projectPath "${{ github.workspace }}" \
            -executeMethod Packages.Rider.Editor.RiderScriptEditor.SyncSolution \
            -logFile -

      - name: Restore Projects
        run: dotnet restore "${{ env.SOLUTION_FILE }}"

      - name: Run Code Analysis
        id: code-analysis
        run: |
          dotnet build "${{ env.SOLUTION_FILE }}" \
            -p:EnforceCodeStyleInBuild=true \
            -p:RunAnalyzersDuringBuild=true \
            -p:EnableNETAnalyzers=true \
            -p:AnalysisLevel=latest \
            -p:NoWarn=MSB3277 \
            -p:WarningLevel=2 \
            -warnaserror \
            --no-incremental

      - name: Check Formatting
        id: format-check
        run: |
          dotnet format "${{ env.LINT_PROJECT_FILE }}" --verify-no-changes --severity error
